# Generated by Django 4.2.1 on 2023-10-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inductor',
            name='costo_indirecto_asociado',
        ),
        migrations.AddField(
            model_name='actividad',
            name='costo_indirecto_asociado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
