# Generated by Django 4.2.1 on 2023-10-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='categoria',
            field=models.CharField(choices=[('Debe', 'Debe'), ('Haber', 'Haber')], default='', max_length=5),
        ),
    ]
