# Generated by Django 4.2.1 on 2023-10-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('Servicio', 'Servicio'), ('Compra', 'Compra')], default='', max_length=50),
        ),
    ]
